import type { ScoreDocument } from "@/modules/score/types";

const PPQ = 480;

export const DEMO_SCORE: ScoreDocument = {
  id: "demo-morning-walk",
  title: "Morning Walk Demo",
  tempo: 96,
  timeSignature: [4, 4],
  ppq: PPQ,
  measures: [
    {
      index: 0,
      startTick: 0,
      endTick: PPQ * 4,
    },
    {
      index: 1,
      startTick: PPQ * 4,
      endTick: PPQ * 8,
    },
  ],
  tracks: [
    {
      id: "right-hand",
      name: "Right Hand",
      clef: "treble",
      notes: [
        {
          id: "rh-1",
          midi: 60,
          pitchName: "C4",
          startTick: 0,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
        {
          id: "rh-2",
          midi: 64,
          pitchName: "E4",
          startTick: PPQ,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
        {
          id: "rh-3",
          midi: 67,
          pitchName: "G4",
          startTick: PPQ * 2,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
        {
          id: "rh-4",
          midi: 72,
          pitchName: "C5",
          startTick: PPQ * 3,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
        {
          id: "rh-5",
          midi: 71,
          pitchName: "B4",
          startTick: PPQ * 4,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
        {
          id: "rh-6",
          midi: 67,
          pitchName: "G4",
          startTick: PPQ * 5,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
        {
          id: "rh-7",
          midi: 64,
          pitchName: "E4",
          startTick: PPQ * 6,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
        {
          id: "rh-8",
          midi: 60,
          pitchName: "C4",
          startTick: PPQ * 7,
          durationTick: PPQ,
          velocity: 0.86,
          staff: 1,
          hand: "R",
        },
      ],
    },
    {
      id: "left-hand",
      name: "Left Hand",
      clef: "bass",
      notes: [
        {
          id: "lh-1",
          midi: 48,
          pitchName: "C3",
          startTick: 0,
          durationTick: PPQ * 2,
          velocity: 0.74,
          staff: 2,
          hand: "L",
        },
        {
          id: "lh-2",
          midi: 55,
          pitchName: "G3",
          startTick: PPQ * 2,
          durationTick: PPQ * 2,
          velocity: 0.74,
          staff: 2,
          hand: "L",
        },
        {
          id: "lh-3",
          midi: 53,
          pitchName: "F3",
          startTick: PPQ * 4,
          durationTick: PPQ * 2,
          velocity: 0.74,
          staff: 2,
          hand: "L",
        },
        {
          id: "lh-4",
          midi: 48,
          pitchName: "C3",
          startTick: PPQ * 6,
          durationTick: PPQ * 2,
          velocity: 0.74,
          staff: 2,
          hand: "L",
        },
      ],
    },
  ],
  source: {
    type: "manual",
    importedAt: "2026-05-04",
  },
};
